### PR TITLE
Update code to use argparse

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Gets rid of argument parsing code and just relies on argparse. Also used black for formatting the code (it's py3 ready if we want to move now)

---

**Related issue :**

### CODE REVIEW

**Comment by enolfc** [comment]
just realised this should be rebased to #6. So we should wait for that

**Comment by gwarf** [comment]
I just merge #6.

**Comment by enolfc** [comment]
Ready

**Comment by enolfc** [comment]
Apparently the linter is not checking the python code. I guess because it's not a `.py`?

**Comment by gwarf** [comment]
> Apparently the linter is not checking the python code. I guess because it's not a `.py`?

I would expect that the `file sbin/glite-info-static` call that seems to be done should identify the file as python code, cf https://github.com/github/super-linter/blob/8607445fb4e3c208841ab4dd78d71d8f6c9923a5/lib/functions/detectFiles.sh#L225-L277

**Comment by gwarf** [comment]
See also https://github.com/github/super-linter/issues/2357
It would be needed to dig in the test output, look more.

**Comment by enolfc** [comment]
Apparently the python code detection works: https://github.com/EGI-Federation/glite-info-static/actions/runs/4305115387/jobs/7507094762#step:5:66
But then the code is not checked 🤷

**Comment by gwarf** [comment]
:/
Maybe you could try to explicitly enable the python linters in the workflow file and see if changes anything?

Like with:
```yaml
VALIDATE_PYTHON: true
VALIDATE_PYTHON_BLACK: true
VALIDATE_PYTHON_FLAKE8: true
VALIDATE_PYTHON_ISORT: true
VALIDATE_PYTHON_MYPY: true
VALIDATE_PYTHON_PYLINT: true
```

**Comment by gwarf** [comment]
You may also want to force the linting of all the codebase to test.

**Comment by enolfc** [comment]
> You may also want to force the linting of all the codebase to test.

I haven't managed to get the file properly linted, even if explicitly setting the PYTHON linters, but don't have enough bandwidth to deal with it at the moment :(

**Comment by gwarf** [comment]
> > You may also want to force the linting of all the codebase to test.
> 
> I haven't managed to get the file properly linted, even if explicitly setting the PYTHON linters, but don't have enough bandwidth to deal with it at the moment :(

We should probably try to run it in debug and/or locally, but I noticed this:

- In `detectFiles.sh` the file should be added to `FILE_ARRAY_PYTHON` variable after the `file` test in https://github.com/github/super-linter/blob/e954bee85d84e8ca866c1e14d2bf33e555d85d9b/lib/functions/detectFiles.sh#L270-L282
- Then `linters.sh` is generating variable names for the various arrays, based on the known languages: https://github.com/github/super-linter/blob/e954bee85d84e8ca866c1e14d2bf33e555d85d9b/lib/linter.sh#L395-L399
- But the `LANGUAGE_ARRAY` seems to only contain PYTHON_SOMETHING variables, so looking for vars like`FILE_ARRAY_PYTHON_BLACK` but not for `FILE_ARRAY_PYTHON`:   
https://github.com/github/super-linter/blob/05f34c653f433dfac36856d446a0d624c46c2012/lib/linter.sh#L260-L261

Please have a look to see if I missed something, but it maybe the case it's just a bug in super-linter...

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
